# Generated by Django 3.0.5 on 2021-07-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ingredient'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ingredient',
            options={'verbose_name': 'Ингредиент', 'verbose_name_plural': 'Ингредиенты'},
        ),
        migrations.AddField(
            model_name='ingredient',
            name='measurement_unit',
            field=models.CharField(default='T', max_length=10, verbose_name='Единица измерения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingredient',
            name='name',
            field=models.CharField(default='test', max_length=50, unique=True, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
