# Generated by Django 3.0.5 on 2021-07-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_recipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='amount',
            field=models.ManyToManyField(to='api.Ingredient'),
        ),
    ]
