# Generated by Django 3.0.5 on 2021-07-15 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_ingredient_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='amount',
        ),
    ]
