# Generated by Django 3.0.5 on 2021-07-17 15:09

from django.db import migrations, models
from django.db.migrations.operations.fields import RemoveField


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20210717_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='ingredients'
        ),
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipe', through='api.RecipeIngredient', to='api.Ingredient', verbose_name='Ингредиенты'),
        ),
    ]
